# Generated by Django 5.0.7 on 2024-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('square_foot', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
